layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Javascript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

  - name: React
    web_url: https://github.com/topics/react
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/react/react.png

  - name: Jest
    web_url: https://github.com/topics/sass
    image_url: https://camo.githubusercontent.com/31983294a16a373a7e752b57904f64cc030750db/68747470733a2f2f6a6573746a732e696f2f696d672f6a6573742e706e67

  - name: Open Source
    web_url: https://github.com
    image_url: https://github.githubassets.com/images/modules/logos_page/Octocat.png
